// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
options: DefaultFirebaseOptions.currentPlatform,
);

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_9f1oDgbEQXCh2FsHOY4GjMdaLIqf_3g',
    appId: '1:985610033427:web:9e397c7479b30e6417e2e6',
    messagingSenderId: '985610033427',
    projectId: 'buzz-410519',
    authDomain: 'buzz-410519.firebaseapp.com',
    storageBucket: 'buzz-410519.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiF87nXt1wbVGAmZpvRlJgq9vjPKF3MIA',
    appId: '1:985610033427:android:d1c892ab617a08ed17e2e6',
    messagingSenderId: '985610033427',
    projectId: 'buzz-410519',
    storageBucket: 'buzz-410519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvVIPZhElKXyT_OxZgiqhnBN1JalYCqhM',
    appId: '1:985610033427:ios:8e199d535d49715917e2e6',
    messagingSenderId: '985610033427',
    projectId: 'buzz-410519',
    storageBucket: 'buzz-410519.appspot.com',
    androidClientId: '985610033427-r1rkdc7l31qs8h23i28dnaf80rlu75db.apps.googleusercontent.com',
    iosClientId: '985610033427-r7edi81ha2nbnvrfdicalmcdvh4f7nf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzzMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvVIPZhElKXyT_OxZgiqhnBN1JalYCqhM',
    appId: '1:985610033427:ios:98bb2752d77f0a3417e2e6',
    messagingSenderId: '985610033427',
    projectId: 'buzz-410519',
    storageBucket: 'buzz-410519.appspot.com',
    androidClientId: '985610033427-r1rkdc7l31qs8h23i28dnaf80rlu75db.apps.googleusercontent.com',
    iosClientId: '985610033427-g38tvhgi3sajju2bu8hjr2hdnqanrm27.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzzMe.RunnerTests',
  );
}
