// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb04hIkx9O95EuiywiAf0_nuymnlV43L8',
    appId: '1:278682884751:web:e6c55c9bac0843830d2efa',
    messagingSenderId: '278682884751',
    projectId: 'buzzme-7aeca',
    authDomain: 'buzzme-7aeca.firebaseapp.com',
    storageBucket: 'buzzme-7aeca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa8gEZjBsPtDrGogd12pTFY4Pbupx8XpI',
    appId: '1:278682884751:android:4f6695a3dc6f42170d2efa',
    messagingSenderId: '278682884751',
    projectId: 'buzzme-7aeca',
    storageBucket: 'buzzme-7aeca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCNmY45SPxv68zxp7uYMMvw_buSvv_tBk',
    appId: '1:278682884751:ios:abc3b57126220a490d2efa',
    messagingSenderId: '278682884751',
    projectId: 'buzzme-7aeca',
    storageBucket: 'buzzme-7aeca.appspot.com',
    iosBundleId: 'com.example.buzzMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCNmY45SPxv68zxp7uYMMvw_buSvv_tBk',
    appId: '1:278682884751:ios:3184ccbd8d61a9040d2efa',
    messagingSenderId: '278682884751',
    projectId: 'buzzme-7aeca',
    storageBucket: 'buzzme-7aeca.appspot.com',
    iosBundleId: 'com.example.buzzMe.RunnerTests',
  );
}
